credentials:
  usernames:
    admin:
      email: "admin@example.com"
      name: "Admin Kullanıcı"
      password: "123" # Bu şifreyi istediğinle değiştirebilirsin
cookie:
  expiry_days: 30
  key: "super_secret_key_123"
  name: "mimari_metraj_auth"
preauthorized:
  emails:
    - "admin@example.com"
